// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/wxlbd/nutri-baby-server/internal/application/service"
	"github.com/wxlbd/nutri-baby-server/internal/infrastructure/config"
	"github.com/wxlbd/nutri-baby-server/internal/infrastructure/persistence"
	"github.com/wxlbd/nutri-baby-server/internal/interface/http/handler"
	"github.com/wxlbd/nutri-baby-server/internal/interface/http/router"
)

// Injectors from wire.go:

// InitApp 初始化应用(Wire自动生成) (去家庭化架构)
func InitApp(cfg *config.Config) (*App, error) {
	db, err := persistence.NewDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := persistence.NewUserRepository(db)
	authService := service.NewAuthService(userRepository, cfg)
	authHandler := handler.NewAuthHandler(authService)
	babyRepository := persistence.NewBabyRepository(db)
	babyCollaboratorRepository := persistence.NewBabyCollaboratorRepository(db)
	babyInvitationRepository := persistence.NewBabyInvitationRepository(db)
	vaccinePlanRepository := persistence.NewVaccinePlanRepository(db)
	vaccineRecordRepository := persistence.NewVaccineRecordRepository(db)
	vaccineReminderRepository := persistence.NewVaccineReminderRepository(db)
	vaccineService := service.NewVaccineService(vaccinePlanRepository, vaccineRecordRepository, vaccineReminderRepository, babyRepository)
	babyService := service.NewBabyService(babyRepository, babyCollaboratorRepository, babyInvitationRepository, userRepository, vaccineService)
	babyHandler := handler.NewBabyHandler(babyService)
	feedingRecordRepository := persistence.NewFeedingRecordRepository(db)
	sleepRecordRepository := persistence.NewSleepRecordRepository(db)
	diaperRecordRepository := persistence.NewDiaperRecordRepository(db)
	growthRecordRepository := persistence.NewGrowthRecordRepository(db)
	recordService := service.NewRecordService(babyRepository, feedingRecordRepository, sleepRecordRepository, diaperRecordRepository, growthRecordRepository, babyCollaboratorRepository)
	recordHandler := handler.NewRecordHandler(recordService)
	vaccineHandler := handler.NewVaccineHandler(vaccineService)
	babyVaccinePlanRepository := persistence.NewBabyVaccinePlanRepository(db)
	vaccinePlanService := service.NewVaccinePlanService(babyVaccinePlanRepository, vaccineRecordRepository, vaccineReminderRepository, babyRepository)
	vaccinePlanHandler := handler.NewVaccinePlanHandler(vaccinePlanService)
	syncHandler := handler.NewSyncHandler()
	engine := router.NewRouter(cfg, authHandler, babyHandler, recordHandler, vaccineHandler, vaccinePlanHandler, syncHandler)
	app := NewApp(cfg, engine)
	return app, nil
}
