package service

import (
	"context"
	"strconv"
	"time"

	"go.uber.org/zap"

	"github.com/wxlbd/nutri-baby-server/internal/application/dto"
	"github.com/wxlbd/nutri-baby-server/internal/domain/entity"
	"github.com/wxlbd/nutri-baby-server/internal/domain/repository"
)

// DiaperRecordService 尿布记录服务
type DiaperRecordService struct {
	*BaseRecordService
	diaperRecordRepo repository.DiaperRecordRepository
}

// NewDiaperRecordService 创建尿布记录服务
func NewDiaperRecordService(
	babyRepo repository.BabyRepository,
	collaboratorRepo repository.BabyCollaboratorRepository,
	userRepo repository.UserRepository,
	diaperRecordRepo repository.DiaperRecordRepository,
	logger *zap.Logger,
) *DiaperRecordService {
	return &DiaperRecordService{
		BaseRecordService: NewBaseRecordService(babyRepo, collaboratorRepo, userRepo, logger),
		diaperRecordRepo:  diaperRecordRepo,
	}
}

// CreateDiaperRecord 创建尿布记录
func (s *DiaperRecordService) CreateDiaperRecord(ctx context.Context, openID string, req *dto.CreateDiaperRecordRequest) (*dto.DiaperRecordDTO, error) {
	if err := s.CheckBabyAccess(ctx, req.BabyID, openID); err != nil {
		return nil, err
	}

	// 转换babyID from string to int64
	babyIDInt64, err := strconv.ParseInt(req.BabyID, 10, 64)
	if err != nil {
		return nil, err
	}

	// 获取用户信息以获取UserID
	user, err := s.userRepo.FindByOpenID(ctx, openID)
	if err != nil {
		return nil, err
	}

	changeTime := req.ChangeTime
	if changeTime == 0 {
		changeTime = time.Now().UnixMilli()
	}

	var note *string
	if req.Note != "" {
		note = &req.Note
	}

	record := &entity.DiaperRecord{
		BabyID:    babyIDInt64,
		Time:      changeTime,
		Type:      req.DiaperType,
		Note:      note,
		CreatedBy: user.ID,
		// ID auto-generated by snowflake
		// CreatedAt/UpdatedAt auto-set by GORM
	}

	if err := s.diaperRecordRepo.Create(ctx, record); err != nil {
		return nil, err
	}

	resultNote := ""
	if record.Note != nil {
		resultNote = *record.Note
	}

	return &dto.DiaperRecordDTO{
		RecordID:   strconv.FormatInt(record.ID, 10),
		BabyID:     strconv.FormatInt(record.BabyID, 10),
		DiaperType: record.Type,
		Note:       resultNote,
		ChangeTime: record.Time,
		CreateBy:   strconv.FormatInt(record.CreatedBy, 10),
		CreateTime: record.CreatedAt,
	}, nil
}

// GetDiaperRecords 获取尿布记录列表
func (s *DiaperRecordService) GetDiaperRecords(ctx context.Context, openID string, query *dto.RecordListQuery) ([]dto.DiaperRecordDTO, int64, error) {
	if err := s.CheckBabyAccess(ctx, query.BabyID, openID); err != nil {
		return nil, 0, err
	}

	// 转换babyID from string to int64
	babyIDInt64, err := strconv.ParseInt(query.BabyID, 10, 64)
	if err != nil {
		return nil, 0, err
	}

	records, total, err := s.diaperRecordRepo.FindByBabyID(
		ctx,
		babyIDInt64,
		query.StartTime,
		query.EndTime,
		query.GetPageWithDefault(),
		query.GetPageSizeWithDefault(),
	)
	if err != nil {
		return nil, 0, err
	}

	result := make([]dto.DiaperRecordDTO, 0, len(records))
	for _, record := range records {
		note := ""
		if record.Note != nil {
			note = *record.Note
		}

		result = append(result, dto.DiaperRecordDTO{
			RecordID:   strconv.FormatInt(record.ID, 10),
			BabyID:     strconv.FormatInt(record.BabyID, 10),
			DiaperType: record.Type,
			Note:       note,
			ChangeTime: record.Time,
			CreateBy:   strconv.FormatInt(record.CreatedBy, 10),
			CreateTime: record.CreatedAt,
		})
	}

	return result, total, nil
}

// GetDiaperRecordById 根据ID获取单条尿布记录
func (s *DiaperRecordService) GetDiaperRecordById(ctx context.Context, openID, recordID string) (*dto.DiaperRecordDTO, error) {
	// 转换recordID from string to int64
	recordIDInt64, err := strconv.ParseInt(recordID, 10, 64)
	if err != nil {
		return nil, err
	}

	// 先获取记录
	record, err := s.diaperRecordRepo.FindByID(ctx, recordIDInt64)
	if err != nil {
		s.logger.Error("获取尿布记录失败",
			zap.String("recordID", recordID),
			zap.Error(err))
		return nil, err
	}

	// 验证用户是否有权限访问该宝宝的记录
	if err := s.CheckBabyAccess(ctx, strconv.FormatInt(record.BabyID, 10), openID); err != nil {
		return nil, err
	}

	note := ""
	if record.Note != nil {
		note = *record.Note
	}

	return &dto.DiaperRecordDTO{
		RecordID:   strconv.FormatInt(record.ID, 10),
		BabyID:     strconv.FormatInt(record.BabyID, 10),
		DiaperType: record.Type,
		Note:       note,
		ChangeTime: record.Time,
		CreateBy:   strconv.FormatInt(record.CreatedBy, 10),
		CreateTime: record.CreatedAt,
	}, nil
}

// UpdateDiaperRecord 更新尿布记录
func (s *DiaperRecordService) UpdateDiaperRecord(ctx context.Context, openID, recordID string, req *dto.UpdateDiaperRecordRequest) (*dto.DiaperRecordDTO, error) {
	// 转换recordID from string to int64
	recordIDInt64, err := strconv.ParseInt(recordID, 10, 64)
	if err != nil {
		return nil, err
	}

	// 先获取记录
	record, err := s.diaperRecordRepo.FindByID(ctx, recordIDInt64)
	if err != nil {
		s.logger.Error("获取尿布记录失败",
			zap.String("recordID", recordID),
			zap.Error(err))
		return nil, err
	}

	// 验证权限
	if err := s.CheckBabyAccess(ctx, strconv.FormatInt(record.BabyID, 10), openID); err != nil {
		return nil, err
	}

	// 更新字段 (只更新非nil字段)
	updated := false

	if req.DiaperType != nil && *req.DiaperType != record.Type {
		record.Type = *req.DiaperType
		updated = true
	}

	if req.ChangeTime != nil && *req.ChangeTime != record.Time {
		record.Time = *req.ChangeTime
		updated = true
	}

	if req.Note != nil {
		record.Note = req.Note
		updated = true
	}

	// 如果没有更新任何字段,直接返回
	if !updated {
		s.logger.Info("没有更新任何字段",
			zap.String("recordID", recordID))
		return s.GetDiaperRecordById(ctx, openID, recordID)
	}

	// 保存更新 (UpdatedAt由GORM自动更新)
	if err := s.diaperRecordRepo.Update(ctx, record); err != nil {
		s.logger.Error("更新尿布记录失败",
			zap.String("recordID", recordID),
			zap.Error(err))
		return nil, err
	}

	s.logger.Info("尿布记录更新成功",
		zap.String("recordID", strconv.FormatInt(record.ID, 10)),
		zap.String("babyID", strconv.FormatInt(record.BabyID, 10)))

	// 返回更新后的记录
	return s.GetDiaperRecordById(ctx, openID, recordID)
}

// DeleteDiaperRecord 删除尿布记录
func (s *DiaperRecordService) DeleteDiaperRecord(ctx context.Context, openID, recordID string) error {
	// 转换recordID from string to int64
	recordIDInt64, err := strconv.ParseInt(recordID, 10, 64)
	if err != nil {
		return err
	}

	// 先获取记录
	record, err := s.diaperRecordRepo.FindByID(ctx, recordIDInt64)
	if err != nil {
		s.logger.Error("获取尿布记录失败",
			zap.String("recordID", recordID),
			zap.Error(err))
		return err
	}

	// 验证权限
	if err := s.CheckBabyAccess(ctx, strconv.FormatInt(record.BabyID, 10), openID); err != nil {
		return err
	}

	// 删除记录 (软删除)
	if err := s.diaperRecordRepo.Delete(ctx, recordIDInt64); err != nil {
		s.logger.Error("删除尿布记录失败",
			zap.String("recordID", recordID),
			zap.Error(err))
		return err
	}

	s.logger.Info("尿布记录删除成功",
		zap.String("recordID", recordID),
		zap.String("babyID", strconv.FormatInt(record.BabyID, 10)))

	return nil
}
