/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AIAlertCard: typeof import('./src/components/ai/AIAlertCard.vue')['default']
    AIChart: typeof import('./src/components/charts/AIChart.vue')['default']
    AIInsightCard: typeof import('./src/components/ai/AIInsightCard.vue')['default']
    AIScoreCard: typeof import('./src/components/ai/AIScoreCard.vue')['default']
    BabyCollaboratorsPreview: typeof import('./src/components/BabyCollaboratorsPreview.vue')['default']
    CircleProgress: typeof import('./src/components/common/CircleProgress.vue')['default']
    DailyTipsCard: typeof import('./src/components/DailyTipsCard.vue')['default']
    SubscribeGuide: typeof import('./src/components/SubscribeGuide.vue')['default']
    UChart: typeof import('./src/components/UChart.vue')['default']
    WdBadge: typeof import('wot-design-uni/components/wd-badge/wd-badge.vue')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
    WdCard: typeof import('wot-design-uni/components/wd-card/wd-card.vue')['default']
    WdCell: typeof import('wot-design-uni/components/wd-cell/wd-cell.vue')['default']
    WdCellGroup: typeof import('wot-design-uni/components/wd-cell-group/wd-cell-group.vue')['default']
    WdDatetimePicker: typeof import('wot-design-uni/components/wd-datetime-picker/wd-datetime-picker.vue')['default']
    WdForm: typeof import('wot-design-uni/components/wd-form/wd-form.vue')['default']
    WdIcon: typeof import('wot-design-uni/components/wd-icon/wd-icon.vue')['default']
    WdInput: typeof import('wot-design-uni/components/wd-input/wd-input.vue')['default']
    WdInputNumber: typeof import('wot-design-uni/components/wd-input-number/wd-input-number.vue')['default']
    WdLoading: typeof import('wot-design-uni/components/wd-loading/wd-loading.vue')['default']
    WdLoadmore: typeof import('wot-design-uni/components/wd-loadmore/wd-loadmore.vue')['default']
    WdMessageBox: typeof import('wot-design-uni/components/wd-message-box/wd-message-box.vue')['default']
    WdNavbar: typeof import('wot-design-uni/components/wd-navbar/wd-navbar.vue')['default']
    WdNavbarCapsule: typeof import('wot-design-uni/components/wd-navbar-capsule/wd-navbar-capsule.vue')['default']
    WdNoticeBar: typeof import('wot-design-uni/components/wd-notice-bar/wd-notice-bar.vue')['default']
    WdPopup: typeof import('wot-design-uni/components/wd-popup/wd-popup.vue')['default']
    WdRadio: typeof import('wot-design-uni/components/wd-radio/wd-radio.vue')['default']
    WdRadioGroup: typeof import('wot-design-uni/components/wd-radio-group/wd-radio-group.vue')['default']
    WdSearch: typeof import('wot-design-uni/components/wd-search/wd-search.vue')['default']
    WdStatusTip: typeof import('wot-design-uni/components/wd-status-tip/wd-status-tip.vue')['default']
    WdSwitch: typeof import('wot-design-uni/components/wd-switch/wd-switch.vue')['default']
    WdTab: typeof import('wot-design-uni/components/wd-tab/wd-tab.vue')['default']
    WdTabs: typeof import('wot-design-uni/components/wd-tabs/wd-tabs.vue')['default']
    WdTag: typeof import('wot-design-uni/components/wd-tag/wd-tag.vue')['default']
    WdText: typeof import('wot-design-uni/components/wd-text/wd-text.vue')['default']
    WdTextarea: typeof import('wot-design-uni/components/wd-textarea/wd-textarea.vue')['default']
    WdToast: typeof import('wot-design-uni/components/wd-toast/wd-toast.vue')['default']
  }
}
