/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomNavbar: typeof import('./src/components/custom-navbar/custom-navbar.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutCell: typeof import('nutui-uniapp/components/cell/cell.vue')['default']
    NutCellGroup: typeof import('nutui-uniapp/components/cellgroup/cellgroup.vue')['default']
    NutDatePicker: typeof import('nutui-uniapp/components/datepicker/datepicker.vue')['default']
    NutDialog: typeof import('nutui-uniapp/components/dialog/dialog.vue')['default']
    NutEmpty: typeof import('nutui-uniapp/components/empty/empty.vue')['default']
    NutForm: typeof import('nutui-uniapp/components/form/form.vue')['default']
    NutFormItem: typeof import('nutui-uniapp/components/formitem/formitem.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['default']
    NutInputNumber: typeof import('nutui-uniapp/components/inputnumber/inputnumber.vue')['default']
    NutLoading: typeof import('nutui-uniapp/components/loading/loading.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
    NutRadio: typeof import('nutui-uniapp/components/radio/radio.vue')['default']
    NutRadioGroup: typeof import('nutui-uniapp/components/radiogroup/radiogroup.vue')['default']
    NutSwitch: typeof import('nutui-uniapp/components/switch/switch.vue')['default']
    NutTabPane: typeof import('nutui-uniapp/components/tabpane/tabpane.vue')['default']
    NutTabs: typeof import('nutui-uniapp/components/tabs/tabs.vue')['default']
    NutTextarea: typeof import('nutui-uniapp/components/textarea/textarea.vue')['default']
    SubscribeGuide: typeof import('./src/components/SubscribeGuide.vue')['default']
  }
}
